name = "JD3"
uuid = "19f0c141-4dee-4e90-b3c7-3c8efd004a00"
authors = ["Davi Barreira <davisbarreira@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
